export const bluthumbProblems = [
  {
    number: 2,
    pattern: "Linked List / Math",
    difficulty: "Medium",
    title: "Add Two Numbers",
    notes: "",
    thumb: "white",
  },
  {
    number: 3,
    pattern: "Sliding Window",
    difficulty: "Medium",
    title: "Longest Substring Without Repeating Characters",
    notes: "",
    thumb: "white",
  },
  {
    number: 5,
    pattern: "String",
    difficulty: "Medium",
    title: "Longest Palindromic Substring",
    notes: "",
    thumb: "white",
  },
  {
    number: 9,
    pattern: "Math",
    difficulty: "Easy",
    title: "Palindrome Number",
    notes: "",
    thumb: "white",
  },
  {
    number: 11,
    pattern: "Array / Two Pointers / Greedy",
    difficulty: "Medium",
    title: "Container With Most Water",
    notes: "",
    thumb: "white",
  },
  {
    number: 13,
    pattern: "String",
    difficulty: "Easy",
    title: "Roman to Integer",
    notes: "",
    thumb: "white",
  },
  {
    number: 14,
    pattern: "String",
    difficulty: "Easy",
    title: "Longest Common Prefix",
    notes: "",
    thumb: "white",
  },
  {
    number: 15,
    pattern: "Array / Two Pointers",
    difficulty: "Medium",
    title: "3Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 17,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Letter Combinations of a Phone Number",
    notes: "",
    thumb: "white",
  },
  {
    number: 18,
    pattern: "Array / Two Pointers",
    difficulty: "Medium",
    title: "4Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 19,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Remove Nth Node From End of List",
    notes: "",
    thumb: "white",
  },
  {
    number: 20,
    pattern: "Stack / Hash Map",
    difficulty: "Easy",
    title: "Valid Parentheses",
    notes: "",
    thumb: "white",
  },
  {
    number: 21,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Merge Two Sorted Lists",
    notes: "",
    thumb: "white",
  },
  {
    number: 22,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Generate Parentheses",
    notes: "",
    thumb: "white",
  },
  {
    number: 24,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Swap Nodes in Pairs",
    notes: "",
    thumb: "white",
  },
  {
    number: 28,
    pattern: "Array",
    difficulty: "Medium",
    title: "Find the Index of the First Occurrence in a String",
    notes: "",
    thumb: "white",
  },
  {
    number: 33,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Search in Rotated Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 34,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Find First and Last Position of Element in Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 35,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Search Insert Position",
    notes: "",
    thumb: "white",
  },
  {
    number: 37,
    pattern: "Backtracking",
    difficulty: "Hard",
    title: "Sudoku Solver",
    notes: "",
    thumb: "white",
  },
  {
    number: 38,
    pattern: "Two Pointers",
    difficulty: "Medium",
    title: "Count and Say",
    notes: "",
    thumb: "white",
  },
  {
    number: 39,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Combination Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 40,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Combination Sum II",
    notes: "",
    thumb: "white",
  },
  {
    number: 44,
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    title: "Wildcard Matching",
    notes: "",
    thumb: "white",
  },
  {
    number: 46,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Permutations",
    notes: "",
    thumb: "white",
  },
  {
    number: 47,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Permutations II",
    notes: "",
    thumb: "white",
  },
  {
    number: 48,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Rotate Image",
    notes: "",
    thumb: "white",
  },
  {
    number: 51,
    pattern: "Backtracking",
    difficulty: "Hard",
    title: "N-Queens",
    notes: "",
    thumb: "white",
  },
  {
    number: 54,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Spiral Matrix",
    notes: "",
    thumb: "white",
  },
  {
    number: 56,
    pattern: "Array / Intervals / Greedy",
    difficulty: "Medium",
    title: "Merge Intervals",
    notes: "",
    thumb: "white",
  },
  {
    number: 57,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Insert Interval",
    notes: "",
    thumb: "white",
  },
  {
    number: 61,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Rotate List",
    notes: "",
    thumb: "white",
  },
  {
    number: 62,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Unique Paths",
    notes: "",
    thumb: "white",
  },
  {
    number: 63,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Unique Paths II",
    notes: "",
    thumb: "white",
  },
  {
    number: 64,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Minimum Path Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 66,
    pattern: "Math",
    difficulty: "Easy",
    title: "Plus One",
    notes: "",
    thumb: "white",
  },
  {
    number: 69,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Sqrt(x)",
    notes: "",
    thumb: "white",
  },
  {
    number: 70,
    pattern: "Dynamic Programming",
    difficulty: "Easy",
    title: "Climbing Stairs",
    notes: "",
    thumb: "white",
  },
  {
    number: 72,
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    title: "Edit Distance",
    notes: "",
    thumb: "white",
  },
  {
    number: 73,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Set Matrix Zeroes",
    notes: "",
    thumb: "white",
  },
  {
    number: 74,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Search a 2D Matrix",
    notes: "",
    thumb: "white",
  },
  {
    number: 76,
    pattern: "Sliding Window",
    difficulty: "Hard",
    title: "Minimum Window Substring",
    notes: "",
    thumb: "white",
  },
  {
    number: 77,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Combinations",
    notes: "",
    thumb: "white",
  },
  {
    number: 78,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Subsets",
    notes: "",
    thumb: "white",
  },
  {
    number: 79,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Word Search",
    notes: "",
    thumb: "white",
  },
  {
    number: 83,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Remove Duplicates from Sorted List",
    notes: "",
    thumb: "white",
  },
  {
    number: 86,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Partition List",
    notes: "",
    thumb: "white",
  },
  {
    number: 88,
    pattern: "Array / Two Pointers",
    difficulty: "Easy",
    title: "Merge Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 90,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Subsets II",
    notes: "",
    thumb: "white",
  },
  {
    number: 93,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Restore IP Addresses",
    notes: "",
    thumb: "white",
  },
  {
    number: 94,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Binary Tree Inorder Traversal",
    notes: "",
    thumb: "white",
  },
  {
    number: 98,
    pattern: "Tree / BST / DFS",
    difficulty: "Medium",
    title: "Validate Binary Search Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 100,
    pattern: "Tree / DFS / BFS",
    difficulty: "Easy",
    title: "Same Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 101,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Symmetric Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 102,
    pattern: "Tree / BFS",
    difficulty: "Medium",
    title: "Binary Tree Level Order Traversal",
    notes: "",
    thumb: "white",
  },
  {
    number: 104,
    pattern: "Tree / DFS / BFS",
    difficulty: "Easy",
    title: "Maximum Depth of Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 108,
    pattern: "Tree / BST / DFS",
    difficulty: "Easy",
    title: "Convert Sorted Array to Binary Search Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 110,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Balanced Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 112,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Path Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 115,
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    title: "Distinct Subsequences",
    notes: "",
    thumb: "white",
  },
  {
    number: 116,
    pattern: "Tree / BFS",
    difficulty: "Medium",
    title: "Populating Next Right Pointers in Each Node",
    notes: "",
    thumb: "white",
  },
  {
    number: 118,
    pattern: "Array",
    difficulty: "Easy",
    title: "Pascal's Triangle",
    notes: "",
    thumb: "white",
  },
  {
    number: 120,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Triangle",
    notes: "",
    thumb: "white",
  },
  {
    number: 121,
    pattern: "Dynamic Programming",
    difficulty: "Easy",
    title: "Best Time to Buy and Sell Stock",
    notes: "",
    thumb: "white",
  },
  {
    number: 122,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Best Time to Buy and Sell Stock II",
    notes: "",
    thumb: "white",
  },
  {
    number: 123,
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    title: "Best Time to Buy and Sell Stock III",
    notes: "",
    thumb: "white",
  },
  {
    number: 124,
    pattern: "Tree / DFS",
    difficulty: "Hard",
    title: "Binary Tree Maximum Path Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 125,
    pattern: "String / Two Pointers",
    difficulty: "Easy",
    title: "Valid Palindrome",
    notes: "",
    thumb: "white",
  },
  {
    number: 127,
    pattern: "String / Hash Set / BFS",
    difficulty: "Hard",
    title: "Word Ladder",
    notes: "",
    thumb: "white",
  },
  {
    number: 133,
    pattern: "Graph / DFS / BFS",
    difficulty: "Medium",
    title: "Clone Graph",
    notes: "",
    thumb: "white",
  },
  {
    number: 138,
    pattern: "Linked List / Hash Map",
    difficulty: "Medium",
    title: "Copy List with Random Pointer",
    notes: "",
    thumb: "white",
  },
  {
    number: 141,
    pattern: "Linked List / Slow & Fast",
    difficulty: "Easy",
    title: "Linked List Cycle",
    notes: "",
    thumb: "white",
  },
  {
    number: 144,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Binary Tree Preorder Traversal",
    notes: "",
    thumb: "white",
  },
  {
    number: 148,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Sort List",
    notes: "",
    thumb: "white",
  },
  {
    number: 150,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Evaluate Reverse Polish Notation",
    notes: "",
    thumb: "white",
  },
  {
    number: 153,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Find Minimum in Rotated Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 155,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Min Stack",
    notes: "",
    thumb: "white",
  },
  {
    number: 160,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Intersection of Two Linked Lists",
    notes: "",
    thumb: "white",
  },
  {
    number: 167,
    pattern: "Array / Two Pointers",
    difficulty: "Medium",
    title: "Two Sum II - Input Array Is Sorted",
    notes: "",
    thumb: "white",
  },
  {
    number: 169,
    pattern: "Array",
    difficulty: "Easy",
    title: "Majority Element",
    notes: "",
    thumb: "white",
  },
  {
    number: 173,
    pattern: "Tree / BST / Stack",
    difficulty: "Medium",
    title: "Binary Search Tree Iterator",
    notes: "",
    thumb: "white",
  },
  {
    number: 188,
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    title: "Best Time to Buy and Sell Stock IV",
    notes: "",
    thumb: "white",
  },
  {
    number: 198,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "House Robber",
    notes: "",
    thumb: "white",
  },
  {
    number: 200,
    pattern: "Matrix / DFS / BFS",
    difficulty: "Medium",
    title: "Number of Islands",
    notes: "",
    thumb: "white",
  },
  {
    number: 202,
    pattern: "Math",
    difficulty: "Easy",
    title: "Happy Number",
    notes: "",
    thumb: "white",
  },
  {
    number: 203,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Remove Linked List Elements",
    notes: "",
    thumb: "white",
  },
  {
    number: 204,
    pattern: "Math",
    difficulty: "Medium",
    title: "Count Primes",
    notes: "",
    thumb: "white",
  },
  {
    number: 205,
    pattern: "String",
    difficulty: "Easy",
    title: "Isomorphic Strings",
    notes: "",
    thumb: "white",
  },
  {
    number: 206,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Reverse Linked List",
    notes: "",
    thumb: "white",
  },
  {
    number: 207,
    pattern: "Graph / DFS / Topological Sort",
    difficulty: "Medium",
    title: "Course Schedule",
    notes: "",
    thumb: "white",
  },
  {
    number: 208,
    pattern: "Trie",
    difficulty: "Medium",
    title: "Implement Trie (Prefix Tree)",
    notes: "",
    thumb: "white",
  },
  {
    number: 210,
    pattern: "Graph / DFS / Topological Sort",
    difficulty: "Medium",
    title: "Course Schedule II",
    notes: "",
    thumb: "white",
  },
  {
    number: 212,
    pattern: "Trie / Backtracking",
    difficulty: "Hard",
    title: "Word Search II",
    notes: "",
    thumb: "white",
  },
  {
    number: 216,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Combination Sum III",
    notes: "",
    thumb: "white",
  },
  {
    number: 217,
    pattern: "Array / Hash Set",
    difficulty: "Easy",
    title: "Contains Duplicate",
    notes: "",
    thumb: "white",
  },
  {
    number: 222,
    pattern: "Tree / DFS / BFS",
    difficulty: "Medium",
    title: "Count Complete Tree Nodes",
    notes: "",
    thumb: "white",
  },
  {
    number: 225,
    pattern: "Stack / Queue",
    difficulty: "Easy",
    title: "Implement Stack using Queues",
    notes: "",
    thumb: "white",
  },
  {
    number: 226,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Invert Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 230,
    pattern: "Tree / BST / DFS",
    difficulty: "Medium",
    title: "Kth Smallest Element in a BST",
    notes: "",
    thumb: "white",
  },
  {
    number: 232,
    pattern: "Stack",
    difficulty: "Easy",
    title: "Implement Queue using Stacks",
    notes: "",
    thumb: "white",
  },
  {
    number: 232,
    pattern: "Queue",
    difficulty: "Easy",
    title: "Implement Queue using Stacks",
    notes: "",
    thumb: "white",
  },
  {
    number: 234,
    pattern: "Linked List / Slow & Fast",
    difficulty: "Easy",
    title: "Palindrome Linked List",
    notes: "",
    thumb: "white",
  },
  {
    number: 236,
    pattern: "Tree / DFS",
    difficulty: "Medium",
    title: "Lowest Common Ancestor of a Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 238,
    pattern: "Array",
    difficulty: "Medium",
    title: "Product of Array Except Self",
    notes: "",
    thumb: "white",
  },
  {
    number: 239,
    pattern: "Sliding Window",
    difficulty: "Hard",
    title: "Sliding Window Maximum",
    notes: "",
    thumb: "white",
  },
  {
    number: 252,
    pattern: "Array / Intervals",
    difficulty: "Easy",
    title: "Meeting Rooms",
    notes: "",
    thumb: "white",
  },
  {
    number: 253,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Meeting Rooms II",
    notes: "",
    thumb: "white",
  },
  {
    number: 257,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Binary Tree Paths",
    notes: "",
    thumb: "white",
  },
  {
    number: 261,
    pattern: "Graph / DFS / BFS / Union Find",
    difficulty: "Medium",
    title: "Graph Valid Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 263,
    pattern: "Math",
    difficulty: "Easy",
    title: "Ugly Number",
    notes: "",
    thumb: "white",
  },
  {
    number: 269,
    pattern: "Graph / DFS / Topological Sort",
    difficulty: "Hard",
    title: "Alien Dictionary",
    notes: "",
    thumb: "white",
  },
  {
    number: 271,
    pattern: "String",
    difficulty: "Medium",
    title: "Encode and Decode Strings",
    notes: "",
    thumb: "white",
  },
  {
    number: 278,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "First Bad Version",
    notes: "",
    thumb: "white",
  },
  {
    number: 285,
    pattern: "Tree / BFS / DFS",
    difficulty: "Medium",
    title: "Inorder Successor in BST",
    notes: "",
    thumb: "white",
  },
  {
    number: 286,
    pattern: "Matrix / BFS",
    difficulty: "Medium",
    title: "Walls and Gates",
    notes: "",
    thumb: "white",
  },
  {
    number: 295,
    pattern: "Heap",
    difficulty: "Hard",
    title: "Find Median from Data Stream",
    notes: "",
    thumb: "white",
  },
  {
    number: 297,
    pattern: "Tree / DFS / BFS",
    difficulty: "Hard",
    title: "Serialize and Deserialize Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 300,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Longest Increasing Subsequence",
    notes: "",
    thumb: "white",
  },
  {
    number: 309,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Best Time to Buy and Sell Stock with Cooldown",
    notes: "",
    thumb: "white",
  },
  {
    number: 314,
    pattern: "Tree / Hash Map",
    difficulty: "Medium",
    title: "Binary Tree Vertical Order Traversal",
    notes: "",
    thumb: "white",
  },
  {
    number: 322,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Coin Change",
    notes: "",
    thumb: "white",
  },
  {
    number: 323,
    pattern: "Graph / DFS / BFS / Union Find",
    difficulty: "Medium",
    title: "Number of Connected Components in an Undirected Graph",
    notes: "",
    thumb: "white",
  },
  {
    number: 344,
    pattern: "String / Two Pointers",
    difficulty: "Easy",
    title: "Reverse String",
    notes: "",
    thumb: "white",
  },
  {
    number: 346,
    pattern: "Queue",
    difficulty: "Easy",
    title: "Moving Average from Data Stream",
    notes: "",
    thumb: "white",
  },
  {
    number: 362,
    pattern: "Queue",
    difficulty: "Medium",
    title: "Design Hit Counter",
    notes: "",
    thumb: "white",
  },
  {
    number: 374,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Guess Number Higher or Lower",
    notes: "",
    thumb: "white",
  },
  {
    number: 382,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Linked List Random Node",
    notes: "",
    thumb: "white",
  },
  {
    number: 392,
    pattern: "String / Two Pointers",
    difficulty: "Easy",
    title: "Is Subsequence",
    notes: "",
    thumb: "white",
  },
  {
    number: 394,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Decode String",
    notes: "",
    thumb: "white",
  },
  {
    number: 402,
    pattern: "Stack / Monotonic Stack",
    difficulty: "Medium",
    title: "Remove K Digits",
    notes: "",
    thumb: "white",
  },
  {
    number: 409,
    pattern: "String / Hash Map",
    difficulty: "Easy",
    title: "Longest Palindrome",
    notes: "",
    thumb: "white",
  },
  {
    number: 435,
    pattern: "Array / Intervals / Greedy",
    difficulty: "Medium",
    title: "Non-overlapping Intervals",
    notes: "",
    thumb: "white",
  },
  {
    number: 438,
    pattern: "Sliding Window",
    difficulty: "Medium",
    title: "Find all Anagrams in a String",
    notes: "",
    thumb: "white",
  },
  {
    number: 441,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Arranging Coins",
    notes: "",
    thumb: "white",
  },
  {
    number: 451,
    pattern: "String / Hash Map / Counting Sort",
    difficulty: "Medium",
    title: "Sort Characters by Frequency",
    notes: "",
    thumb: "white",
  },
  {
    number: 452,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Minimum Number of Arrows to Burst Balloons",
    notes: "",
    thumb: "white",
  },
  {
    number: 463,
    pattern: "Matrix / DFS / BFS",
    difficulty: "Easy",
    title: "Island Perimeter",
    notes: "",
    thumb: "white",
  },
  {
    number: 473,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Matchsticks to Square",
    notes: "",
    thumb: "white",
  },
  {
    number: 490,
    pattern: "Matrix / BFS",
    difficulty: "Medium",
    title: "The Maze",
    notes: "",
    thumb: "white",
  },
  {
    number: 496,
    pattern: "Stack / Monotonic Stack",
    difficulty: "Easy",
    title: "Next Greater Element I",
    notes: "",
    thumb: "white",
  },
  {
    number: 503,
    pattern: "Stack / Monotonic Stack",
    difficulty: "Medium",
    title: "Next Greater Element II",
    notes: "",
    thumb: "white",
  },
  {
    number: 509,
    pattern: "Dynamic Programming",
    difficulty: "Easy",
    title: "Fibonacci Number",
    notes: "",
    thumb: "white",
  },
  {
    number: 518,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Coin Change II",
    notes: "",
    thumb: "white",
  },
  {
    number: 526,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Beautiful Arrangement",
    notes: "",
    thumb: "white",
  },
  {
    number: 540,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Single Element in a Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 542,
    pattern: "Matrix / BFS",
    difficulty: "Medium",
    title: "01 Matrix",
    notes: "",
    thumb: "white",
  },
  {
    number: 543,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Diameter of Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 545,
    pattern: "Tree / DFS",
    difficulty: "Medium",
    title: "Boundary Of Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 560,
    pattern: "Array",
    difficulty: "Medium",
    title: "Subarray Sum Equals K",
    notes: "",
    thumb: "white",
  },
  {
    number: 621,
    pattern: "Heap / Greedy",
    difficulty: "Medium",
    title: "Task Scheduler",
    notes: "",
    thumb: "white",
  },
  {
    number: 648,
    pattern: "Trie / Hash Set",
    difficulty: "Medium",
    title: "Replace Words",
    notes: "",
    thumb: "white",
  },
  {
    number: 662,
    pattern: "Tree / BFS",
    difficulty: "Medium",
    title: "Maximum Width of Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 678,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Valid Parenthesis String",
    notes: "",
    thumb: "white",
  },
  {
    number: 680,
    pattern: "String / Two Pointers",
    difficulty: "Easy",
    title: "Valid Palindrome II",
    notes: "",
    thumb: "white",
  },
  {
    number: 684,
    pattern: "Graph / Union Find",
    difficulty: "Medium",
    title: "Redundant Connection",
    notes: "",
    thumb: "white",
  },
  {
    number: 694,
    pattern: "Matrix / DFS / BFS",
    difficulty: "Medium",
    title: "Number of Distinct Islands",
    notes: "",
    thumb: "white",
  },
  {
    number: 700,
    pattern: "Tree / BST / DFS",
    difficulty: "Easy",
    title: "Search in a Binary Search Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 701,
    pattern: "Tree / BST / DFS",
    difficulty: "Medium",
    title: "Insert into a Binary Search Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 704,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Binary Search",
    notes: "",
    thumb: "white",
  },
  {
    number: 704,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Binary Search",
    notes: "",
    thumb: "white",
  },
  {
    number: 714,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Best Time to Buy and Sell Stock with Transaction Fee",
    notes: "",
    thumb: "white",
  },
  {
    number: 724,
    pattern: "Array",
    difficulty: "Easy",
    title: "Find Pivot Index",
    notes: "",
    thumb: "white",
  },
  {
    number: 739,
    pattern: "Stack / Monotonic Stack",
    difficulty: "Medium",
    title: "Daily Temperatures",
    notes: "",
    thumb: "white",
  },
  {
    number: 746,
    pattern: "Dynamic Programming",
    difficulty: "Easy",
    title: "Min Cost Climbing Stairs",
    notes: "",
    thumb: "white",
  },
  {
    number: 752,
    pattern: "String / BFS",
    difficulty: "Medium",
    title: "Open the Lock",
    notes: "",
    thumb: "white",
  },
  {
    number: 783,
    pattern: "Tree / BST / DFS",
    difficulty: "Easy",
    title: "Minimum Distance Between BST Nodes",
    notes: "",
    thumb: "white",
  },
  {
    number: 787,
    pattern: "Graph / BFS / Dijkstras",
    difficulty: "Medium",
    title: "Cheapest Flights Within K Stops",
    notes: "",
    thumb: "white",
  },
  {
    number: 791,
    pattern: "String / Hash Map",
    difficulty: "Medium",
    title: "Custom Sort String",
    notes: "",
    thumb: "white",
  },
  {
    number: 797,
    pattern: "Graph / DFS",
    difficulty: "Medium",
    title: "All Paths From Source to Target",
    notes: "",
    thumb: "white",
  },
  {
    number: 802,
    pattern: "Graph / DFS / Topological Sort",
    difficulty: "Medium",
    title: "Find Eventual Safe States",
    notes: "",
    thumb: "white",
  },
  {
    number: 807,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Max Increase to Keep City Skyline",
    notes: "",
    thumb: "white",
  },
  {
    number: 815,
    pattern: "Graph / Hash Map / BFS",
    difficulty: "Hard",
    title: "Bus Routes",
    notes: "",
    thumb: "white",
  },
  {
    number: 821,
    pattern: "String",
    difficulty: "Easy",
    title: "Shortest Distance to a Character",
    notes: "",
    thumb: "white",
  },
  {
    number: 841,
    pattern: "Array / BFS",
    difficulty: "Medium",
    title: "Keys and Rooms",
    notes: "",
    thumb: "white",
  },
  {
    number: 844,
    pattern: "String / Stack",
    difficulty: "Easy",
    title: "Backspace String Compare",
    notes: "",
    thumb: "white",
  },
  {
    number: 848,
    pattern: "String",
    difficulty: "Medium",
    title: "Shifting Letters",
    notes: "",
    thumb: "white",
  },
  {
    number: 849,
    pattern: "Sliding Window",
    difficulty: "Medium",
    title: "Maximize Distance to Closest Person",
    notes: "",
    thumb: "white",
  },
  {
    number: 852,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Peak Index in a Mountain Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 853,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Car Fleet",
    notes: "",
    thumb: "white",
  },
  {
    number: 859,
    pattern: "String",
    difficulty: "Easy",
    title: "Buddy Strings",
    notes: "",
    thumb: "white",
  },
  {
    number: 863,
    pattern: "Tree / DFS / BFS",
    difficulty: "Medium",
    title: "All Nodes Distance K in Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 875,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Koko Eating Bananas",
    notes: "",
    thumb: "white",
  },
  {
    number: 876,
    pattern: "Linked List / Slow & Fast",
    difficulty: "Easy",
    title: "Middle of the Linked List",
    notes: "",
    thumb: "white",
  },
  {
    number: 881,
    pattern: "Array / Two Pointers / Greedy",
    difficulty: "Medium",
    title: "Boats to Save People",
    notes: "",
    thumb: "white",
  },
  {
    number: 901,
    pattern: "Stack / Monotonic Stack",
    difficulty: "Medium",
    title: "Online Stock Span",
    notes: "",
    thumb: "white",
  },
  {
    number: 915,
    pattern: "Array / Suffix Sum",
    difficulty: "Medium",
    title: "Partition Array into Disjoint Intervals",
    notes: "",
    thumb: "white",
  },
  {
    number: 917,
    pattern: "Two Pointers / String",
    difficulty: "Easy",
    title: "Reverse Only Letters",
    notes: "",
    thumb: "white",
  },
  {
    number: 934,
    pattern: "Matrix / DFS / BFS",
    difficulty: "Medium",
    title: "Shortest Bridge",
    notes: "",
    thumb: "white",
  },
  {
    number: 944,
    pattern: "String",
    difficulty: "Easy",
    title: "Delete Columns to Make Sorted",
    notes: "",
    thumb: "white",
  },
  {
    number: 945,
    pattern: "Array / Greedy",
    difficulty: "Medium",
    title: "Minimum Increment to Make Array Unique",
    notes: "",
    thumb: "white",
  },
  {
    number: 946,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Validate Stack Sequences",
    notes: "",
    thumb: "white",
  },
  {
    number: 949,
    pattern: "Array",
    difficulty: "Medium",
    title: "Largest Time for Given Digits",
    notes: "",
    thumb: "white",
  },
  {
    number: 977,
    pattern: "Array / Two Pointers",
    difficulty: "Easy",
    title: "Squares of a Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 980,
    pattern: "Matrix / DFS",
    difficulty: "Hard",
    title: "Unique Paths III",
    notes: "",
    thumb: "white",
  },
  {
    number: 981,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Time Based Key-Value Store",
    notes: "",
    thumb: "white",
  },
  {
    number: 994,
    pattern: "Matrix / BFS",
    difficulty: "Medium",
    title: "Rotting Oranges",
    notes: "",
    thumb: "white",
  },
  {
    number: 1010,
    pattern: "Math",
    difficulty: "Medium",
    title: "Pairs of Songs With Total Durations Divisible by 60",
    notes: "",
    thumb: "white",
  },
  {
    number: 1011,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Capacity To Ship Packages Within D Days",
    notes: "",
    thumb: "white",
  },
  {
    number: 1020,
    pattern: "Matrix / DFS / BFS",
    difficulty: "Medium",
    title: "Number of Enclaves",
    notes: "",
    thumb: "white",
  },
  {
    number: 1048,
    pattern: "Dynamic Programming",
    difficulty: "Nedium",
    title: "Longest String Chain",
    notes: "",
    thumb: "white",
  },
  {
    number: 1065,
    pattern: "String / Trie",
    difficulty: "Easy",
    title: "Index Pairs of a String",
    notes: "",
    thumb: "white",
  },
  {
    number: 1071,
    pattern: "String",
    difficulty: "Easy",
    title: "Greatest Common Divisor of Strings",
    notes: "",
    thumb: "white",
  },
  {
    number: 1079,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Letter Tile Possibilities",
    notes: "",
    thumb: "white",
  },
  {
    number: 1086,
    pattern: "Heap",
    difficulty: "Easy",
    title: "High Five",
    notes: "",
    thumb: "white",
  },
  {
    number: 1087,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Brace Expansion",
    notes: "",
    thumb: "white",
  },
  {
    number: 1091,
    pattern: "Graph / Queue / BFS",
    difficulty: "Medium",
    title: "Shortest Path in Binary Matrix",
    notes: "",
    thumb: "white",
  },
  {
    number: 1093,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Statistics from a Large Sample",
    notes: "",
    thumb: "white",
  },
  {
    number: 1128,
    pattern: "Array / Hash Map",
    difficulty: "Easy",
    title: "Number of Equivalent Domino Pairs",
    notes: "",
    thumb: "white",
  },
  {
    number: 1143,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Longest Common Subsequence",
    notes: "",
    thumb: "white",
  },
  {
    number: 1167,
    pattern: "Heap / Greedy",
    difficulty: "Medium",
    title: "Minimum Cost to Connect Sticks",
    notes: "",
    thumb: "white",
  },
  {
    number: 1175,
    pattern: "Math",
    difficulty: "Medium",
    title: "Prime Arrangements",
    notes: "",
    thumb: "white",
  },
  {
    number: 1176,
    pattern: "Sliding Window",
    difficulty: "Easy",
    title: "Diet Plan Performance",
    notes: "",
    thumb: "white",
  },
  {
    number: 1209,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Remove All Adjacent Duplicates in String II",
    notes: "",
    thumb: "white",
  },
  {
    number: 1219,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Path with Maximum Gold",
    notes: "",
    thumb: "white",
  },
  {
    number: 1222,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Queens That Can Attack the King",
    notes: "",
    thumb: "white",
  },
  {
    number: 1245,
    pattern: "Tree / DFS / BFS",
    difficulty: "Medium",
    title: "Tree Diameter",
    notes: "",
    thumb: "white",
  },
  {
    number: 1260,
    pattern: "Matrix / Math",
    difficulty: "Easy",
    title: "Shift 2D Grid",
    notes: "",
    thumb: "white",
  },
  {
    number: 1265,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Print Immutable Linked List in Reverse",
    notes: "",
    thumb: "white",
  },
  {
    number: 1288,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Remove Covered Intervals",
    notes: "",
    thumb: "white",
  },
  {
    number: 1296,
    pattern: "Heap / Hash Map / Greedy",
    difficulty: "Medium",
    title: "Divide Array in Sets of K Consecutive Numbers",
    notes: "",
    thumb: "white",
  },
  {
    number: 1299,
    pattern: "Array",
    difficulty: "Easy",
    title: "Replace Elements with Greatest Element on Right Side",
    notes: "",
    thumb: "white",
  },
  {
    number: 1312,
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    title: "Minimum Insertion Steps to Make a String Palindrome",
    notes: "",
    thumb: "white",
  },
  {
    number: 1315,
    pattern: "Tree / DFS",
    difficulty: "Medium",
    title: "Sum of Nodes with Even-Valued Grandparent",
    notes: "",
    thumb: "white",
  },
  {
    number: 1319,
    pattern: "Graph / Union Find",
    difficulty: "Medium",
    title: "Number of Operations to Make Network Connected",
    notes: "",
    thumb: "white",
  },
  {
    number: 1324,
    pattern: "String",
    difficulty: "Medium",
    title: "Print Words Vertically",
    notes: "",
    thumb: "white",
  },
  {
    number: 1329,
    pattern: "Matrix / Heap",
    difficulty: "Medium",
    title: "Sort the Matrix Diagonally",
    notes: "",
    thumb: "white",
  },
  {
    number: 1334,
    pattern: "Graph / Floyd-Warshall",
    difficulty: "Medium",
    title:
      "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
    notes: "",
    thumb: "white",
  },
  {
    number: 1347,
    pattern: "String",
    difficulty: "Medium",
    title: "Minimum Number of Steps to Make Two Strings Anagram",
    notes: "",
    thumb: "white",
  },
  {
    number: 1351,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Count Negative Numbers in a Sorted Matrix",
    notes: "",
    thumb: "white",
  },
  {
    number: 1352,
    pattern: "Array / Prefix Sum",
    difficulty: "Medium",
    title: "Product of the Last K Numbers",
    notes: "",
    thumb: "white",
  },
  {
    number: 1358,
    pattern: "Sliding Window",
    difficulty: "Medium",
    title: "Number of Substrings Containing All Three Characters",
    notes: "",
    thumb: "white",
  },
  {
    number: 1370,
    pattern: "String",
    difficulty: "Easy",
    title: "Increasing Decreasing String",
    notes: "",
    thumb: "white",
  },
  {
    number: 1390,
    pattern: "Math",
    difficulty: "Medium",
    title: "Four Divisors",
    notes: "",
    thumb: "white",
  },
  {
    number: 1423,
    pattern: "Sliding Window",
    difficulty: "Medium",
    title: "Maximum Points You Can Obtain from Cards",
    notes: "",
    thumb: "white",
  },
  {
    number: 1427,
    pattern: "String",
    difficulty: "Easy",
    title: "Perform String Shifts",
    notes: "",
    thumb: "white",
  },
  {
    number: 1455,
    pattern: "String",
    difficulty: "Easy",
    title: "Check If a Word Occurs As a Prefix of Any Word in a Sentence",
    notes: "",
    thumb: "white",
  },
  {
    number: 1463,
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    title: "Cherry Pickup II",
    notes: "",
    thumb: "white",
  },
  {
    number: 1464,
    pattern: "Heap",
    difficulty: "Easy",
    title: "Maximum Product of Two Elements in an Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 1472,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Design Browser History",
    notes: "",
    thumb: "white",
  },
  {
    number: 1498,
    pattern: "Two Pointers",
    difficulty: "Medium",
    title: "Number of Subsequences That Satisfy the Given Sum Condition",
    notes: "",
    thumb: "white",
  },
  {
    number: 1506,
    pattern: "Tree / Hash Map",
    difficulty: "Medium",
    title: "Find Root of N-Ary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 1529,
    pattern: "String / Greedy",
    difficulty: "Medium",
    title: "Minimum Suffix Flips",
    notes: "",
    thumb: "white",
  },
  {
    number: 1535,
    pattern: "Queue",
    difficulty: "Medium",
    title: "Find the Winner of an Array Game",
    notes: "",
    thumb: "white",
  },
  {
    number: 1561,
    pattern: "Heap / Greedy",
    difficulty: "Medium",
    title: "Maximum Number of Coins You Can Get",
    notes: "",
    thumb: "white",
  },
  {
    number: 1584,
    pattern: "Graph / Prims / Kruskals",
    difficulty: "Medium",
    title: "Min Cost to Connect All Points",
    notes: "",
    thumb: "white",
  },
  {
    number: 1637,
    pattern: "Math",
    difficulty: "Medium",
    title: "Widest Vertical Area Between Two Points Containing No Points",
    notes: "",
    thumb: "white",
  },
  {
    number: 1647,
    pattern: "String / Greedy",
    difficulty: "Medium",
    title: "Minimum Deletions to Make Character Frequencies Unique",
    notes: "",
    thumb: "white",
  },
  {
    number: 1650,
    pattern: "Tree / Hash Set",
    difficulty: "Medium",
    title: "Lowest Common Ancestor of a Binary Tree III",
    notes: "",
    thumb: "white",
  },
  {
    number: 1668,
    pattern: "String",
    difficulty: "Easy",
    title: "Maximum Repeating Substring",
    notes: "",
    thumb: "white",
  },
  {
    number: 1669,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Merge In Between Linked Lists",
    notes: "",
    thumb: "white",
  },
  {
    number: 1679,
    pattern: "Array / Two Pointers",
    difficulty: "Medium",
    title: "Max Number of K-Sum Pairs",
    notes: "",
    thumb: "white",
  },
  {
    number: 1721,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Swapping Nodes in a Linked List",
    notes: "",
    thumb: "white",
  },
  {
    number: 1730,
    pattern: "Matrix / BFS",
    difficulty: "Medium",
    title: "Shortest Path to Get Food",
    notes: "",
    thumb: "white",
  },
  {
    number: 1740,
    pattern: "Tree / BFS",
    difficulty: "Medium",
    title: "Find Distance in a Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 1753,
    pattern: "Heap",
    difficulty: "Medium",
    title: "Maximum Score From Removing Stones",
    notes: "",
    thumb: "white",
  },
  {
    number: 1758,
    pattern: "String",
    difficulty: "Easy",
    title: "Minimum Changes to Make Alternating Binary String",
    notes: "",
    thumb: "white",
  },
  {
    number: 1785,
    pattern: "Array / Greedy",
    difficulty: "Medium",
    title: "Minimum Elements to Add to Form a Given Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 1807,
    pattern: "String / Hash Map / Two Pointers",
    difficulty: "Medium",
    title: "Evaluate the Bracket Pairs of a String",
    notes: "",
    thumb: "white",
  },
  {
    number: 1827,
    pattern: "Array",
    difficulty: "Easy",
    title: "Minimum Operations to Make the Array Increasing",
    notes: "",
    thumb: "white",
  },
  {
    number: 1836,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Remove Duplicates From an Unsorted Linked List",
    notes: "",
    thumb: "white",
  },
  {
    number: 1838,
    pattern: "Sliding Window",
    difficulty: "Medium",
    title: "Frequency of the Most Frequent Element",
    notes: "",
    thumb: "white",
  },
  {
    number: 1874,
    pattern: "Array / Hash Map / Greedy / Counting Sort",
    difficulty: "Medium",
    title: "Minimize Product Sum of Two Arrays",
    notes: "",
    thumb: "white",
  },
  {
    number: 1894,
    pattern: "Math",
    difficulty: "Medium",
    title: "Find the Student that Will Replace the Chalk",
    notes: "",
    thumb: "white",
  },
  {
    number: 1903,
    pattern: "String / Greedy",
    difficulty: "Easy",
    title: "Largest Odd Number in String",
    notes: "",
    thumb: "white",
  },
  {
    number: 1904,
    pattern: "Math",
    difficulty: "Medium",
    title: "The Number of Full Rounds You Have Played",
    notes: "",
    thumb: "white",
  },
  {
    number: 1909,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Remove One Element to Make the Array Strictly Increasing",
    notes: "",
    thumb: "white",
  },
  {
    number: 1913,
    pattern: "Array",
    difficulty: "Easy",
    title: "Maximum Product Difference Between Two Pairs",
    notes: "",
    thumb: "white",
  },
  {
    number: 1930,
    pattern: "Array / Hash Set",
    difficulty: "Medium",
    title: "Unique Length-3 Palindromic Subsequences",
    notes: "",
    thumb: "white",
  },
  {
    number: 1974,
    pattern: "String / Math",
    difficulty: "Easy",
    title: "Minimum Time to Type WOrd Using Special Typewriter",
    notes: "",
    thumb: "white",
  },
  {
    number: 1976,
    pattern: "Graph / Dijkstras",
    difficulty: "Medium",
    title: "Number of Ways to Arrive at Destination",
    notes: "",
    thumb: "white",
  },
  {
    number: 1980,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Find Unique Binary String",
    notes: "",
    thumb: "white",
  },
  {
    number: 1984,
    pattern: "Sliding Window",
    difficulty: "Easy",
    title: "Minimum Difference Between Highest and Lowest of K Scores",
    notes: "",
    thumb: "white",
  },
  {
    number: 1985,
    pattern: "Heap",
    difficulty: "Meidum",
    title: "Find the Kth Largest Integer in the Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 2012,
    pattern: "Array / Prefix Sum / Suffix Sum",
    difficulty: "Medium",
    title: "Sum of Beauty in the Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 2037,
    pattern: "Array / Greedy",
    difficulty: "Easy",
    title: "Minimum Number of Moves to Seat Everyone",
    notes: "",
    thumb: "white",
  },
  {
    number: 2062,
    pattern: "String / Hash Set",
    difficulty: "Easy",
    title: "Count Vowel Substrings of a String",
    notes: "",
    thumb: "white",
  },
  {
    number: 2099,
    pattern: "Heap",
    difficulty: "Easy",
    title: "Find Subsequence of Length K With the Largest Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 2107,
    pattern: "Sliding Window",
    difficulty: "Medium",
    title: "Number of Unique Flavors After Sharing K Candies",
    notes: "",
    thumb: "white",
  },
  {
    number: 2129,
    pattern: "String",
    difficulty: "Easy",
    title: "Capitalize the Title",
    notes: "",
    thumb: "white",
  },
  {
    number: 2161,
    pattern: "Array",
    difficulty: "Medium",
    title: "Partition Array According to Given Pivot",
    notes: "",
    thumb: "white",
  },
  {
    number: 2181,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Merge Nodes in Between Zeros",
    notes: "",
    thumb: "white",
  },
  {
    number: 2194,
    pattern: "String",
    difficulty: "Easy",
    title: "Cells in a Range on an Excel Sheet",
    notes: "",
    thumb: "white",
  },
  {
    number: 2224,
    pattern: "String",
    difficulty: "Easy",
    title: "Minimum Number of Operations to Convert Time",
    notes: "",
    thumb: "white",
  },
  {
    number: 2259,
    pattern: "String / Greedy",
    difficulty: "Easy",
    title: "Remove Digit From Number to Maximize Result",
    notes: "",
    thumb: "white",
  },
  {
    number: 2268,
    pattern: "String / Greedy / Counting Sort",
    difficulty: "Medium",
    title: "Minimum Number of Keypresses",
    notes: "",
    thumb: "white",
  },
  {
    number: 2383,
    pattern: "Array / Greedy",
    difficulty: "Easy",
    title: "Minimum Hours of Training to Win a Competition",
    notes: "",
    thumb: "white",
  },
  {
    number: 2389,
    pattern: "Binary Search",
    difficulty: "Easy",
    title: "Longest Subsequence With Limited Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 2390,
    pattern: "Stack",
    difficulty: "Medium",
    title: "Removing Stars From a String",
    notes: "",
    thumb: "white",
  },
  {
    number: 2399,
    pattern: "String / Hash Map",
    difficulty: "Easy",
    title: "Check Distances Between Same Letters",
    notes: "",
    thumb: "white",
  },
  {
    number: 2405,
    pattern: "String / Hash Set / Greedy",
    difficulty: "Medium",
    title: "Optimal Partition of String",
    notes: "",
    thumb: "white",
  },
  {
    number: 2410,
    pattern: "Array / Greedy",
    difficulty: "Medium",
    title: "Maximum Matching of Players With Trainers",
    notes: "",
    thumb: "white",
  },
  {
    number: 2416,
    pattern: "Trie",
    difficulty: "Hard",
    title: "Sum of Prefix Scores of Strings",
    notes: "",
    thumb: "white",
  },
  {
    number: 2501,
    pattern: "Array / Hash Set",
    difficulty: "Medium",
    title: "Longest Square Streak in an Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 2507,
    pattern: "Math",
    difficulty: "Medium",
    title: "Smallest Value After Replacing With Sum of Prime Factors",
    notes: "",
    thumb: "white",
  },
  {
    number: 2515,
    pattern: "Array",
    difficulty: "Easy",
    title: "Shortest Distance to Target String in a Circular Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 2535,
    pattern: "Array",
    difficulty: "Easy",
    title: "Difference Between Element Sum and Digit Sum of an Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 2544,
    pattern: "Math",
    difficulty: "Easy",
    title: "Alternating Digit Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 2554,
    pattern: "Array / Hash Set / Greedy",
    difficulty: "Medium",
    title: "Maximum Number of Integers to Choose From a Range I",
    notes: "",
    thumb: "white",
  },
  {
    number: 2559,
    pattern: "Array / Prefix Sum",
    difficulty: "Medium",
    title: "Count Vowel Strings in Ranges",
    notes: "",
    thumb: "white",
  },
  {
    number: 2566,
    pattern: "Integer / Greedy",
    difficulty: "Easy",
    title: "Maximum Difference by Remapping a Digit",
    notes: "",
    thumb: "white",
  },
];

export const blind75Problems = [
  {
    number: 1,
    pattern: "Hash Map",
    difficulty: "Easy",
    title: "Two Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 3,
    pattern: "String / Hash Table / Sliding Window",
    difficulty: "Medium",
    title: "Longest Substring Without Repeating Characters",
    notes: "",
    thumb: "white",
  },
  {
    number: 5,
    pattern: "String / Two Pointers",
    difficulty: "Medium",
    title: "Longest Palindromic Substring",
    notes: "",
    thumb: "white",
  },
  {
    number: 11,
    pattern: "Two Pointers",
    difficulty: "Medium",
    title: "Container With Most Water",
    notes: "",
    thumb: "white",
  },
  {
    number: 15,
    pattern: "Two Pointers",
    difficulty: "Medium",
    title: "3Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 19,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Remove Nth Node From End of List",
    notes: "",
    thumb: "white",
  },
  {
    number: 20,
    pattern: "String / Stack",
    difficulty: "Easy",
    title: "Valid Parentheses",
    notes: "",
    thumb: "white",
  },
  {
    number: 21,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Merge Two Sorted Lists",
    notes: "",
    thumb: "white",
  },
  {
    number: 23,
    pattern: "Linked List",
    difficulty: "Hard",
    title: "Merge k Sorted Lists",
    notes: "",
    thumb: "white",
  },
  {
    number: 33,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Search in Rotated Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 48,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Rotate Image",
    notes: "",
    thumb: "white",
  },
  {
    number: 49,
    pattern: "String / Hash Map",
    difficulty: "Medium",
    title: "Group Anagrams",
    notes: "",
    thumb: "white",
  },
  {
    number: 53,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Maximum Subarray",
    notes: "",
    thumb: "white",
  },
  {
    number: 54,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Spiral Matrix",
    notes: "",
    thumb: "white",
  },
  {
    number: 55,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Jump Game",
    notes: "",
    thumb: "white",
  },
  {
    number: 56,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Merge Intervals",
    notes: "",
    thumb: "white",
  },
  {
    number: 57,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Insert Interval",
    notes: "",
    thumb: "white",
  },
  {
    number: 62,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Unique Paths",
    notes: "",
    thumb: "white",
  },
  {
    number: 70,
    pattern: "Dynamic Programming",
    difficulty: "Easy",
    title: "Climbing Stairs",
    notes: "",
    thumb: "white",
  },
  {
    number: 73,
    pattern: "Matrix",
    difficulty: "Medium",
    title: "Set Matrix Zeroes",
    notes: "",
    thumb: "white",
  },
  {
    number: 76,
    pattern: "String / Hash Table / Sliding Window",
    difficulty: "Hard",
    title: "Minimum Window Substring",
    notes: "",
    thumb: "white",
  },
  {
    number: 79,
    pattern: "Backtracking",
    difficulty: "Medium",
    title: "Word Search",
    notes: "",
    thumb: "white",
  },
  {
    number: 91,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Decode Ways",
    notes: "",
    thumb: "white",
  },
  {
    number: 98,
    pattern: "Tree / DFS",
    difficulty: "Medium",
    title: "Validate Binary Search Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 100,
    pattern: "Tree / DFS / BFS",
    difficulty: "Easy",
    title: "Same Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 102,
    pattern: "Tree / BFS",
    difficulty: "Medium",
    title: "Binary Tree Level Order Traversal",
    notes: "",
    thumb: "white",
  },
  {
    number: 104,
    pattern: "Tree / DFS / BFS",
    difficulty: "Easy",
    title: "Maximum Depth of Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 105,
    pattern: "Tree / DFS",
    difficulty: "Medium",
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    notes: "",
    thumb: "white",
  },
  {
    number: 121,
    pattern: "Dynamic Programming",
    difficulty: "Easy",
    title: "Best Time to Buy and Sell Stock",
    notes: "",
    thumb: "white",
  },
  {
    number: 124,
    pattern: "Tree / DFS",
    difficulty: "Hard",
    title: "Binary Tree Maximum Path Sum",
    notes: "",
    thumb: "white",
  },
  {
    number: 125,
    pattern: "String / Two Pointers",
    difficulty: "Easy",
    title: "Valid Palindrome",
    notes: "",
    thumb: "white",
  },
  {
    number: 128,
    pattern: "Array / Hash Set",
    difficulty: "Medium",
    title: "Longest Consecutive Sequence",
    notes: "",
    thumb: "white",
  },
  {
    number: 133,
    pattern: "Graph / DFS / BFS",
    difficulty: "Medium",
    title: "Clone Graph",
    notes: "",
    thumb: "white",
  },
  {
    number: 139,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Word break",
    notes: "",
    thumb: "white",
  },
  {
    number: 141,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Linked List Cycle",
    notes: "",
    thumb: "white",
  },
  {
    number: 143,
    pattern: "Linked List",
    difficulty: "Medium",
    title: "Reorder List",
    notes: "",
    thumb: "white",
  },
  {
    number: 152,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Maximum Product Subarray",
    notes: "",
    thumb: "white",
  },
  {
    number: 153,
    pattern: "Binary Search",
    difficulty: "Medium",
    title: "Find Minimum in Rotated Sorted Array",
    notes: "",
    thumb: "white",
  },
  {
    number: 190,
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    title: "Reverse Bits",
    notes: "",
    thumb: "white",
  },
  {
    number: 191,
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    title: "Number of 1 Bits",
    notes: "",
    thumb: "white",
  },
  {
    number: 198,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "House Robber",
    notes: "",
    thumb: "white",
  },
  {
    number: 200,
    pattern: "Matrix / DFS / BFS",
    difficulty: "Medium",
    title: "Number of Islands",
    notes: "",
    thumb: "white",
  },
  {
    number: 206,
    pattern: "Linked List",
    difficulty: "Easy",
    title: "Reverse Linked List",
    notes: "",
    thumb: "white",
  },
  {
    number: 207,
    pattern: "Graph / DFS / BFS / Topological Sort / DAG",
    difficulty: "Medium",
    title: "Course Schedule",
    notes: "",
    thumb: "white",
  },
  {
    number: 208,
    pattern: "Trie",
    difficulty: "Medium",
    title: "Implement Trie (Prefix Tree)",
    notes: "",
    thumb: "white",
  },
  {
    number: 211,
    pattern: "Trie",
    difficulty: "Medium",
    title: "Design Add and Search Words Data Structure",
    notes: "",
    thumb: "white",
  },
  {
    number: 212,
    pattern: "Trie / Backtracking",
    difficulty: "Hard",
    title: "Word Search II",
    notes: "",
    thumb: "white",
  },
  {
    number: 213,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "House Robber II",
    notes: "",
    thumb: "white",
  },
  {
    number: 217,
    pattern: "Hash Set",
    difficulty: "Easy",
    title: "Contains Duplicate",
    notes: "",
    thumb: "white",
  },
  {
    number: 226,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Invert Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 230,
    pattern: "Tree / DFS",
    difficulty: "Medium",
    title: "Kth Smallest Element in a BST",
    notes: "",
    thumb: "white",
  },
  {
    number: 235,
    pattern: "Tree / DFS",
    difficulty: "Medium",
    title: "Lowest Common Ancestor of a Binary Search Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 238,
    pattern: "Array",
    difficulty: "Medium",
    title: "Product of Array Except Self",
    notes: "",
    thumb: "white",
  },
  {
    number: 242,
    pattern: "Array / Hash Table",
    difficulty: "Easy",
    title: "Valid Anagram",
    notes: "",
    thumb: "white",
  },
  {
    number: 252,
    pattern: "Array / Intervals",
    difficulty: "Easy",
    title: "Meeting Rooms",
    notes: "",
    thumb: "white",
  },
  {
    number: 253,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Meeting Rooms II",
    notes: "",
    thumb: "white",
  },
  {
    number: 261,
    pattern: "Graph / DFS / BFS / Union-Find",
    difficulty: "Medium",
    title: "Graph Valid Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 268,
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    title: "Missing Number",
    notes: "",
    thumb: "white",
  },
  {
    number: 269,
    pattern: "Graph / DFS / BFS / Topological Sort",
    difficulty: "Hard",
    title: "Alien Dictionary",
    notes: "",
    thumb: "white",
  },
  {
    number: 271,
    pattern: "String",
    difficulty: "Medium",
    title: "Encode and Decode Strings",
    notes: "",
    thumb: "white",
  },
  {
    number: 295,
    pattern: "Heap",
    difficulty: "Hard",
    title: "Find Median from Data Stream",
    notes: "",
    thumb: "white",
  },
  {
    number: 297,
    pattern: "Tree",
    difficulty: "Hard",
    title: "Serialize and Deserialize Binary Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 300,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Longest Increasing Subsequence",
    notes: "",
    thumb: "white",
  },
  {
    number: 322,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Coin Change",
    notes: "",
    thumb: "white",
  },
  {
    number: 323,
    pattern: "Graph / DFS / BFS / Union-Find",
    difficulty: "Medium",
    title: "Number of Connected Components in an Undirected Graph",
    notes: "",
    thumb: "white",
  },
  {
    number: 338,
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    title: "Counting Bits",
    notes: "",
    thumb: "white",
  },
  {
    number: 347,
    pattern: "Heap",
    difficulty: "Medium",
    title: "Top K Frequent Elements",
    notes: "",
    thumb: "white",
  },
  {
    number: 371,
    pattern: "Bit Manipulation",
    difficulty: "Medium",
    title: "Sum of Two Integers",
    notes: "",
    thumb: "white",
  },
  {
    number: 377,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Combination Sum IV",
    notes: "",
    thumb: "white",
  },
  {
    number: 417,
    pattern: "Matrix / DFS",
    difficulty: "Medium",
    title: "Pacific Atlantic Water Flow",
    notes: "",
    thumb: "white",
  },
  {
    number: 424,
    pattern: "String / Hash Table / Sliding Window",
    difficulty: "Medium",
    title: "Longest Repeating Character Replacement",
    notes: "",
    thumb: "white",
  },
  {
    number: 435,
    pattern: "Array / Intervals",
    difficulty: "Medium",
    title: "Non-overlapping Intervals",
    notes: "",
    thumb: "white",
  },
  {
    number: 572,
    pattern: "Tree / DFS",
    difficulty: "Easy",
    title: "Subtree of Another Tree",
    notes: "",
    thumb: "white",
  },
  {
    number: 647,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Palindromic Substrings",
    notes: "",
    thumb: "white",
  },
  {
    number: 1143,
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    title: "Longest Common Subsequence",
    notes: "",
    thumb: "white",
  },
];

export default { bluthumbProblems, blind75Problems };
